### Train, Valid, Test
- **train** and **valid** are sampled from 3 horizonal consecutive grids, used to train and validate our model.
- **test** is sampled from 3 vertical consecutive grids. They are actually used for signal map imputation. There are 54 missing grids in total. Their coordinates are stored in `test_points`.

- There are 2400000 samples for **train**
- There are 480000 samples for **valid**
- There are 54 $\times$ 12000 samples for **test** (12000 samples for each grid, and 54 grids)

### Datatype

- `train_input`, `train_gt`, `valid_input`, `valid_gt`: the sample coordinates are not recorded because these data are only for GAN training instead of signal map imputation. Datatype: **(sample number, left/mid/right, AP)**
  
- `test_input`, `test_gt`: the generated data will later be used for signal map generation, so the coordinates are specified. There are 54 coordinates, so we have the datatype: **(54, sample number, left/mid/right, AP)**. Through the first dimention we can find the coordiates through `test_points` (in the exact order).




In [1]:
import numpy as np

In [16]:
train_input = np.load('train_input.npy')
train_gt = np.load('train_gt.npy')
valid_input = np.load('valid_input.npy')
valid_gt = np.load('valid_gt.npy')
test_input = np.load('test_input.npy')
test_gt = np.load('test_gt.npy')
test_input = np.load('test_input.npy')
test_input = test_input.transpose(0,1,3,2)
test_gt = np.load('test_gt.npy')
test_gt = test_gt.transpose(0,1,3,2)

print('train_input shape:', train_input.shape)
print('train_gt shape:', train_gt.shape)
print('valid_input shape:', valid_input.shape)
print('valid_gt shape:', valid_gt.shape)
print('test_input shape:', test_input.shape)
print('test_gt shape:', test_gt.shape)

train_input shape: (2400000, 3, 4)
train_gt shape: (2400000, 3, 4)
valid_input shape: (480000, 3, 4)
valid_gt shape: (480000, 3, 4)
test_input shape: (54, 12000, 4, 3)
test_gt shape: (54, 12000, 4, 3)


In [20]:
test_input = test_input[:54,:1200,:,:]
test_input.reshape(-1,4,3)[:5]

array([[[-46. , -44. , -42. ],
        [-48. , -48.5, -49. ],
        [-51. , -51. , -51. ],
        [-61. , -60. , -59. ]],

       [[-46. , -46.5, -47. ],
        [-52. , -49. , -46. ],
        [-51. , -51. , -51. ],
        [-59. , -60. , -61. ]],

       [[-46. , -44.5, -43. ],
        [-49. , -49. , -49. ],
        [-51. , -51. , -51. ],
        [-60. , -60.5, -61. ]],

       [[-46. , -44.5, -43. ],
        [-48. , -47. , -46. ],
        [-52. , -51.5, -51. ],
        [-60. , -60. , -60. ]],

       [[-46. , -45. , -44. ],
        [-48. , -49. , -50. ],
        [-51. , -51. , -51. ],
        [-59. , -60. , -61. ]]])

In [21]:
test_gt = test_gt[:54,:1200,:,:]
test_gt.reshape(-1,4,3)[:5]

array([[[-46., -44., -42.],
        [-48., -50., -49.],
        [-51., -52., -51.],
        [-61., -59., -59.]],

       [[-46., -44., -47.],
        [-52., -48., -46.],
        [-51., -50., -51.],
        [-59., -60., -61.]],

       [[-46., -45., -43.],
        [-49., -51., -49.],
        [-51., -51., -51.],
        [-60., -60., -61.]],

       [[-46., -44., -43.],
        [-48., -49., -46.],
        [-52., -52., -51.],
        [-60., -58., -60.]],

       [[-46., -44., -44.],
        [-48., -50., -50.],
        [-51., -51., -51.],
        [-59., -60., -61.]]])

In [3]:
test_points = np.load('test_points.npy')
for x, y in test_points:
    print('x', x, 'y', y)

x 0 y 1
x 0 y 3
x 0 y 5
x 0 y 7
x 0 y 9
x 0 y 11
x 0 y 13
x 0 y 15
x 0 y 17
x 1 y 1
x 1 y 3
x 1 y 5
x 1 y 7
x 1 y 9
x 1 y 11
x 1 y 13
x 1 y 15
x 1 y 17
x 2 y 1
x 2 y 3
x 2 y 5
x 2 y 7
x 2 y 9
x 2 y 11
x 2 y 13
x 2 y 15
x 2 y 17
x 3 y 1
x 3 y 3
x 3 y 5
x 3 y 7
x 3 y 9
x 3 y 11
x 3 y 13
x 3 y 15
x 3 y 17
x 4 y 1
x 4 y 3
x 4 y 5
x 4 y 7
x 4 y 9
x 4 y 11
x 4 y 13
x 4 y 15
x 4 y 17
x 5 y 1
x 5 y 3
x 5 y 5
x 5 y 7
x 5 y 9
x 5 y 11
x 5 y 13
x 5 y 15
x 5 y 17


In [4]:
train_input[0:2]

array([[[-48. , -46. , -51. , -59. ],
        [-51.5, -46.5, -52.5, -60. ],
        [-55. , -47. , -54. , -61. ]],

       [[-44. , -50. , -50. , -60. ],
        [-49.5, -48.5, -50. , -61. ],
        [-55. , -47. , -50. , -62. ]]])

In [14]:
print(train_input.transpose(0,2,1)[0,:,:])
print(train_gt.transpose(0,2,1)[0,:,:])

[[-48.  -51.5 -55. ]
 [-46.  -46.5 -47. ]
 [-51.  -52.5 -54. ]
 [-59.  -60.  -61. ]]
[[-48. -45. -55.]
 [-46. -46. -47.]
 [-51. -50. -54.]
 [-59. -65. -61.]]


In [15]:
print(train_input.transpose(0,2,1)[0,:,1])
print(train_gt.transpose(0,2,1)[0,:,1])

[-51.5 -46.5 -52.5 -60. ]
[-45. -46. -50. -65.]
